name: Deploy Docs to GH Pages

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - name: Configuring git
      run: |
        git config --global user.email "deploy-bot@paradigmpost.com"
        git config --global user.name "Deploy Bot"
    - name: Configuring ssh
      run: echo "${{ secrets.DEPLOY_KEY }}" > ~/deploy_key && chmod 600 ~/deploy_key
    - name: Building docs and deploying
      run: GIT_SSH_COMMAND='ssh -i ~/deploy_key' ./deploy.sh
